### ISSUE TITLE
DateTimeImmutableMicrosecondsType does not work for MariaDBPlatform

### ISSUE THREAD

**Issue by wazum** [headsnet/domain-events-bundle#28]
MariaDBPlatform extends MySQLPlatform and not MySQL57Platform which is used in DateTimeImmutableMicrosecondsType

```
class MariaDBPlatform extends MySQLPlatform
```

**Comment by benr77** [comment]
Would using a precision of 6 via a `DATETIME(6)` column break on MySQL 5.0 or just be silently ignored? I don't have an install I can test on very easily. 

I'm not sure we should even care, as MySQL 5.5 support ended December 2018 and 5.6 in February 2021. The minimum supported Symfony version of the bundle is 4.4, so I guess it will not be used by any particularly old applications.

So unless you have anything else to add I'd suggest we go for it and replace `MySQL57Platform` with `MySQLPlatform`.

**Comment by wazum** [comment]
No, go ahead! Thanks

**Comment by benr77** [comment]
Ok done and tagged new release `v0.1.9`
