### ISSUE TITLE
Performance bottleneck because of flush in the DoctrineEventStore

### ISSUE THREAD

**Issue by wazum** [headsnet/domain-events-bundle#30]
Calling `flush` for every stored event in the `publish` method
```php
    public function publish(StoredEvent $storedEvent): void
    {
        $storedEvent->setPublishedOn(new DateTimeImmutable());
        $this->em->persist($storedEvent);
        $this->em->flush();
    }
```
is a worse performance bottleneck.
I would suggest injecting the entity manager and moving the flush call to the `PublishDomainEventSubscriber`
```php
    private function publishEvents(): void
    {
        foreach ($this->eventStore->allUnpublished() as $event) {
            $this->publishEvent($event);
        }
        $this->entityManager->flush();
    }
```
That speeds up processing a lot!
Does something speak against it @benr77?

**Comment by benr77** [comment]
My concern with this change is that you could publish a set of events, and then the flush could fail, meaning the same events would be published again.

We don't offer a "publish once" promise, so I'm not against this change, but it's definitely something to consider.

Also, the publishing happens in the KERNEL_TERMINATE stage of the request, so the performance hit should not be noticeable to the end user, only the server load.

**Comment by wazum** [comment]
You're right, it might have some bad side effects too calling flush at this place, I close the issue.
