### ISSUE TITLE
Request: Update dependencies

### ISSUE THREAD

**Issue by wazum** [headsnet/domain-events-bundle#5]
I'm already using Symfony 5.1 for a project, I suggest to update the version constraints.
Please let me know how you prefer to specify the version numbers (see example attached), so that I can make a suitable pull request.

![Screenshot 2020-08-06 14 23 47](https://user-images.githubusercontent.com/146727/89531526-acd53c00-d7f0-11ea-9362-8624a322d7bc.png)

**Comment by benr77** [comment]
Ok, well we need a minimum of 4.4 for the 4.x branch, plus I think it should just work from 5.0 upwards, but it's not been tested. Please can you submit PRs for any issues that crop up running under Symfony 5.x

The constraints for the Symfony packages should be:

```
    "symfony/framework-bundle": "^4.4 || ^5.0",
    "symfony/lock": "^4.4 || ^5.0",
    "symfony/serializer": "^4.4 || ^5.0",
    "symfony/messenger": "^4.4 || ^5.0"
```

I think for Doctrine we'll just need to use:

```
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.0",
```

Thanks

**Comment by wazum** [comment]
I'm on it

**Comment by benr77** [comment]
@wazum I've just pushed these changes so don't worry about it - will tag a release for Symfony 5 support in a sec

**Comment by benr77** [comment]
Ok to just confirm we have changed `"doctrine/doctrine-bundle": "^1.0"` to `"doctrine/doctrine-bundle": "^1.0 || ^2.0"` to correctly support Symfony 5.

I have now recreated the Symfony 5 release `v0.1.2` with this amendment.
