### ISSUE TITLE
Request: should we add a note on the outbox pattern?

### ISSUE THREAD

**Issue by wazum** [headsnet/domain-events-bundle#6]
This package implements the outbox pattern such as described here:
http://www.kamilgrzybek.com/design/the-outbox-pattern/
Should we mention that in the documentation?

**Comment by benr77** [comment]
Yes, that would be a good idea. I have already mentioned the Observer pattern in the readme.

I would describe it as:

> an event system based on the Observer pattern, that offers transactional consistency via the Outbox pattern.

Does that sound like an accurate description? Feel free to correct or improve this as I'm not 100% sure!
