### ISSUE TITLE
Question: Effect of two lines in \Headsnet\DomainEventsBundle\Doctrine\DoctrineEventStore::append

### ISSUE THREAD

**Issue by wazum** [headsnet/domain-events-bundle#7]
https://github.com/headsnet/domain-events-bundle/blob/6b4e4b76d24c81493228d3eaf36618112f4598ae/src/Doctrine/DoctrineEventStore.php#L71-L72

What do these lines do exactly?
\Doctrine\ORM\UnitOfWork::computeChangeSet is marked as `@internal`

**Comment by benr77** [comment]
Good question. I'm not 100% sure any more as it was 1 year ago and my commit message is not helpful!

It is something to do with flushing the changes, as you cannot call `flush()` directly in the Doctrine lifecycle event listeners.

I also wonder if it might be related to running `bin/console messenger:consume` and processing multiple requests inside a single process - i.e. to reset Doctrine...

Either way you are right it is marked as @internal so clarifying it's purpose and/or replacing with a better alternative is needed.

**Comment by wazum** [comment]
I read more about the details of these methods and `@internal` ("don't call from the outside") includes lifecycle events like 'onFlush' we use here, so that's the correct and only way to achieve this.

**Comment by benr77** [comment]
Ok great thanks for the update!
